apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.app.azureconfig.resourcegroup }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.app.azureconfig.loadbalancerip }}
  ports:
    - port: 80
      targetPort: {{ .Values.app.appconfig.httpport }}
