app: 
  image:
    repository: novatec/technologyconsulting-showcase-supplierdomain
    tag: 
  appconfig:
    httpport: 9080
    httpsport: 9443
    MANUFACTURE_DELIVER_URL: http://manufacturedomain-service:80/manufacturedomain/component/deliver/
    MANUFACTURE_USER: admin
    MANUFACTURE_PASSWORD: adminpwd
  dbconfig:
    host: 
    port: 5432
    user: 
    password: 
    schema: 
    name: 
  scale:
    minReplica: 1
    maxReplicas: 3
  azureconfig:
    resourcegroup: 
    loadbalancerip: 
